
// Code generated by _tools/gen_shims. DO NOT EDIT.

package fourslash

import "github.com/microsoft/TypeScript/tsc/internal/fourslash"
import "github.com/microsoft/TypeScript/tsc/internal/lsp/lsproto"
import "github.com/microsoft/TypeScript/tsc/internal/testutil/lsptestutil"
import "testing"
import "unsafe"

var AnyTextEdits = fourslash.AnyTextEdits
type AppliedQuickFixResult = fourslash.AppliedQuickFixResult
type AppliedRefactorResult = fourslash.AppliedRefactorResult
type ApplyCodeActionFromCompletionOptions = fourslash.ApplyCodeActionFromCompletionOptions
type ClientCapabilitiesOptions = fourslash.ClientCapabilitiesOptions
type CompletionsExpectedCodeAction = fourslash.CompletionsExpectedCodeAction
type CompletionsExpectedItem = fourslash.CompletionsExpectedItem
type CompletionsExpectedItemDefaults = fourslash.CompletionsExpectedItemDefaults
type CompletionsExpectedItems = fourslash.CompletionsExpectedItems
type CompletionsExpectedList = fourslash.CompletionsExpectedList
type EditRange = fourslash.EditRange
type ExpectedCompletionEditRange = fourslash.ExpectedCompletionEditRange
type FileChange = fourslash.FileChange
type FoldingRangeLineExpected = fourslash.FoldingRangeLineExpected
type FourslashOptions = fourslash.FourslashOptions
type FourslashTest = fourslash.FourslashTest
type extra_FourslashTest_client struct {
  client *lsptestutil.LSPClient
}
func FourslashTest_client(v *fourslash.FourslashTest) *lsptestutil.LSPClient {
  return ((*extra_FourslashTest_client)(unsafe.Pointer(v))).client
}
//go:linkname GetDefaultCapabilities github.com/microsoft/TypeScript/tsc/internal/fourslash.GetDefaultCapabilities
func GetDefaultCapabilities() *lsproto.ClientCapabilities
//go:linkname GetDefaultCapabilitiesWithOptions github.com/microsoft/TypeScript/tsc/internal/fourslash.GetDefaultCapabilitiesWithOptions
func GetDefaultCapabilitiesWithOptions(options *fourslash.ClientCapabilitiesOptions) *lsproto.ClientCapabilities
type Ignored = fourslash.Ignored
type Marker = fourslash.Marker
type MarkerInput = fourslash.MarkerInput
type MarkerOrRange = fourslash.MarkerOrRange
type MarkerOrRangeOrName = fourslash.MarkerOrRangeOrName
//go:linkname NewFourslash github.com/microsoft/TypeScript/tsc/internal/fourslash.NewFourslash
func NewFourslash(t *testing.T, capabilities *lsproto.ClientCapabilities, content string) (*fourslash.FourslashTest, func())
//go:linkname NewFourslashWithOptions github.com/microsoft/TypeScript/tsc/internal/fourslash.NewFourslashWithOptions
func NewFourslashWithOptions(t *testing.T, content string, options *fourslash.FourslashOptions) (*fourslash.FourslashTest, func())
var NoTextEdits = fourslash.NoTextEdits
//go:linkname ParseTestData github.com/microsoft/TypeScript/tsc/internal/fourslash.ParseTestData
func ParseTestData(t *testing.T, contents string, fileName string) fourslash.TestData
var PrepareTestFSCallback = fourslash.PrepareTestFSCallback
type QuickFixInfo = fourslash.QuickFixInfo
type RangeMarker = fourslash.RangeMarker
type RefactorActionInfo = fourslash.RefactorActionInfo
//go:linkname RegisterPrepareTestFSCallback github.com/microsoft/TypeScript/tsc/internal/fourslash.RegisterPrepareTestFSCallback
func RegisterPrepareTestFSCallback(cb func(testfs map[string]any))
type SemanticToken = fourslash.SemanticToken
type SignatureHelpCase = fourslash.SignatureHelpCase
type TestData = fourslash.TestData
type TestFileInfo = fourslash.TestFileInfo
type VerifyCodeFixAllOptions = fourslash.VerifyCodeFixAllOptions
type VerifyCodeFixOptions = fourslash.VerifyCodeFixOptions
type VerifyCompletionsResult = fourslash.VerifyCompletionsResult
type VerifySignatureHelpOptions = fourslash.VerifySignatureHelpOptions
type VerifyWorkspaceSymbolCase = fourslash.VerifyWorkspaceSymbolCase
