import * as NodeFileSystem from "@effect/platform-node/NodeFileSystem"
import * as NodePath from "@effect/platform-node/NodePath"
import * as Effect from "effect/Effect"
import * as FileSystem from "effect/FileSystem"
import * as Layer from "effect/Layer"
import * as Path from "effect/Path"
import { defineConfig } from "tsdown"

const copyPackageFiles = () => {
  const program = Effect.gen(function*() {
    const fs = yield* FileSystem.FileSystem
    const path = yield* Path.Path

    const readme = yield* fs.readFileString("../../README.md")
    yield* fs.writeFileString(path.join("README.md"), readme)

    const schemaJson = yield* fs.readFileString("../../schema.json")
    yield* fs.writeFileString(path.join("schema.json"), schemaJson)

    const oxlintSchemaJson = yield* fs.readFileString("../../oxlint-schema.json")
    yield* fs.writeFileString(path.join("oxlint-schema.json"), oxlintSchemaJson)

    const presetDirectory = path.join("oxlint-presets")
    yield* fs.remove(presetDirectory, { recursive: true, force: true })
    yield* fs.makeDirectory(presetDirectory)

    const presetSources: Array<string> = []
    const presetSourceDirectory = path.join("../../oxlint-presets")
    const presetFiles = (yield* fs.readDirectory(presetSourceDirectory))
      .filter((name) => name.endsWith(".json"))
      .sort()
    const exportNames: Array<string> = []
    for (const presetFile of presetFiles) {
      const fileName = presetFile.slice(0, -".json".length)
      const exportName = fileName.replace(/-([a-z])/g, (_, letter: string) => letter.toUpperCase())
      const source = yield* fs.readFileString(path.join(presetSourceDirectory, presetFile))
      yield* fs.writeFileString(path.join(presetDirectory, presetFile), source)
      presetSources.push(`export const ${exportName} = ${source.trim()}\n`)
      exportNames.push(exportName)
    }

    const generatedHeader = "// Code generated by the @effect/tsgo package build. DO NOT EDIT.\n\n"
    yield* fs.writeFileString(
      path.join(presetDirectory, "index.js"),
      `${generatedHeader}${presetSources.join("\n")}\nexport const presets = {\n${
        exportNames.map((name) => `  ${name},`).join("\n")
      }\n}\n`
    )
    yield* fs.writeFileString(
      path.join(presetDirectory, "index.d.ts"),
      `${generatedHeader}import type { OxlintConfig } from "oxlint"\n\n${
        exportNames.map((name) => `export declare const ${name}: OxlintConfig`).join("\n")
      }\n\nexport declare const presets: Readonly<{\n${
        exportNames.map((name) => `  ${name}: OxlintConfig`).join("\n")
      }\n}>\n`
    )
  }).pipe(Effect.provide(Layer.merge(NodeFileSystem.layer, NodePath.layerPosix)))

  return Effect.runPromise(program)
}

export default defineConfig({
  entry: {
    "effect-tsgo": "./src/cli/index.ts",
  },
  inlineOnly: false,
  outDir: "./dist",
  format: ["cjs"],
  platform: "node",
  target: "node22",
  dts: false,
  clean: true,
  outExtensions: () => ({
    js: ".cjs",
  }),
  banner: {
    js: "#!/usr/bin/env node",
  },
  onSuccess: copyPackageFiles,
})
