// Code generated by go run ./_tools/gen_etsjsapi; DO NOT EDIT.

export const protocolVersion = 3 as const

export interface CodeAction {
  readonly title: string
  readonly edits: ReadonlyArray<TextEdit>
}

export interface Diagnostic {
  readonly file: string
  readonly start: number
  readonly end: number
  readonly code: number
  readonly ruleName: string
  readonly message: string
  readonly actions?: ReadonlyArray<CodeAction>
}

export interface EffectPluginOptions {
  readonly refactors?: boolean
  readonly diagnostics?: boolean
  readonly includeSuggestionsInTsc?: boolean
  readonly quickinfo?: boolean
  readonly completions?: boolean
  readonly debug?: boolean
  readonly goto?: boolean
  readonly renames?: boolean
  readonly ignoreEffectSuggestionsInTscExitCode?: boolean
  readonly ignoreEffectWarningsInTscExitCode?: boolean
  readonly ignoreEffectErrorsInTscExitCode?: boolean
  readonly skipDisabledOptimization?: boolean
  readonly mermaidProvider?: string
  readonly noExternal?: boolean
  readonly layerGraphFollowDepth?: number
  readonly inlays?: boolean
  readonly namespaceImportPackages?: ReadonlyArray<string>
  readonly barrelImportPackages?: ReadonlyArray<string>
  readonly importAliases?: Readonly<Record<string, string>>
  readonly topLevelNamedReexports?: "ignore" | "follow"
  readonly keyPatterns?: ReadonlyArray<KeyPattern>
  readonly extendedKeyDetection?: boolean
  readonly pipeableMinArgCount?: number
  readonly allowedDuplicatedPackages?: ReadonlyArray<string>
  readonly effectFn?: ReadonlyArray<"span" | "untraced" | "no-span" | "inferred-span" | "suggested-span">
  readonly diagnosticSeverity?: Readonly<Record<string, Severity>>
  readonly overrides?: ReadonlyArray<Override>
}

export interface KeyPattern {
  readonly target?: "service" | "error" | "custom"
  readonly pattern?: "default" | "package-identifier" | "default-hashed"
  readonly skipLeadingPath?: ReadonlyArray<string>
}

export type OptionsSource = "settings" | "tsconfig"

export interface Override {
  readonly include?: ReadonlyArray<string>
  readonly exclude?: ReadonlyArray<string>
  readonly options?: OverrideOptions
}

export interface OverrideOptions {
  readonly diagnosticSeverity?: Readonly<Record<string, Severity>>
  readonly pipeableMinArgCount?: number
  readonly keyPatterns?: ReadonlyArray<KeyPattern>
  readonly extendedKeyDetection?: boolean
  readonly allowedDuplicatedPackages?: ReadonlyArray<string>
  readonly effectFn?: ReadonlyArray<"span" | "untraced" | "no-span" | "inferred-span" | "suggested-span">
}

export interface RunEffectDiagnosticsParams {
  readonly targetFilePath: string
  readonly overrideSourceText?: string
  readonly projectFilePath?: string
  readonly onlyRules?: ReadonlyArray<string> | null
  readonly overrideEffectOptions?: EffectPluginOptions
  readonly includeFixes?: boolean
}

export interface RunEffectDiagnosticsResult {
  readonly diagnostics: ReadonlyArray<Diagnostic>
  readonly optionsSource: OptionsSource
}

export type Severity = "off" | "warning" | "warn" | "error" | "suggestion" | "message" | "skip-file"

export interface TextEdit {
  readonly start: number
  readonly end: number
  readonly newText: string
}

export type TopLevelNamedReexportsMode = "follow" | "ignore"

export interface MethodMap {
  readonly runEffectDiagnostics: {
    readonly params: RunEffectDiagnosticsParams
    readonly result: RunEffectDiagnosticsResult
  }
}

export type Method = keyof MethodMap

export interface WireResponse<M extends Method> {
  readonly version: number
  readonly id: number
  readonly result?: MethodMap[M]["result"]
  readonly error?: { readonly message: string }
}
