
// Code generated by _tools/gen_shims. DO NOT EDIT.

package spanmap

import "github.com/microsoft/TypeScript/tsc/internal/spanmap"
import _ "unsafe"

type Feature = spanmap.Feature
const FeatureAll = spanmap.FeatureAll
const FeatureAutoInsert = spanmap.FeatureAutoInsert
const FeatureCallHierarchy = spanmap.FeatureCallHierarchy
const FeatureCodeActions = spanmap.FeatureCodeActions
const FeatureCodeLens = spanmap.FeatureCodeLens
const FeatureCompletion = spanmap.FeatureCompletion
const FeatureDefinition = spanmap.FeatureDefinition
const FeatureDocumentHighlights = spanmap.FeatureDocumentHighlights
const FeatureDocumentSymbols = spanmap.FeatureDocumentSymbols
const FeatureFoldingRanges = spanmap.FeatureFoldingRanges
const FeatureFormatting = spanmap.FeatureFormatting
const FeatureHover = spanmap.FeatureHover
const FeatureImplementation = spanmap.FeatureImplementation
const FeatureInlayHints = spanmap.FeatureInlayHints
const FeatureLinkedEditing = spanmap.FeatureLinkedEditing
const FeatureNone = spanmap.FeatureNone
const FeatureReferences = spanmap.FeatureReferences
const FeatureRename = spanmap.FeatureRename
const FeatureSelectionRanges = spanmap.FeatureSelectionRanges
const FeatureSemanticTokens = spanmap.FeatureSemanticTokens
const FeatureSignatureHelp = spanmap.FeatureSignatureHelp
const FeatureTypeDefinition = spanmap.FeatureTypeDefinition
type Fidelity = spanmap.Fidelity
const FidelityApproximate = spanmap.FidelityApproximate
const FidelityAtom = spanmap.FidelityAtom
const FidelityExact = spanmap.FidelityExact
const FidelityNone = spanmap.FidelityNone
type Kind = spanmap.Kind
const KindAlias = spanmap.KindAlias
const KindAtom = spanmap.KindAtom
const KindVerbatim = spanmap.KindVerbatim
type MappedPosition = spanmap.MappedPosition
type MappedSpan = spanmap.MappedSpan
type MappingError = spanmap.MappingError
type MappingErrorKind = spanmap.MappingErrorKind
const MappingErrorKindFeature = spanmap.MappingErrorKindFeature
const MappingErrorKindKind = spanmap.MappingErrorKindKind
const MappingErrorKindOutOfBounds = spanmap.MappingErrorKindOutOfBounds
const MappingErrorKindOverlap = spanmap.MappingErrorKindOverlap
const MappingErrorKindVerbatimMismatch = spanmap.MappingErrorKindVerbatimMismatch
//go:linkname New github.com/microsoft/TypeScript/tsc/internal/spanmap.New
func New(segments []spanmap.Segment) *spanmap.SpanMap
type Segment = spanmap.Segment
type SpanMap = spanmap.SpanMap
//go:linkname Unmarshal github.com/microsoft/TypeScript/tsc/internal/spanmap.Unmarshal
func Unmarshal(data []byte) (*spanmap.SpanMap, error)
