# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json

version: "2"

run:
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - copyloopvar
    - bodyclose
    - errcheck
    - errname
    - errorlint
    - gocritic
    - govet
    - ineffassign
    - makezero
    - misspell
    - nolintlint
    - predeclared
    - reassign
    - revive
    - staticcheck
    - unconvert

  settings:
    revive:
      rules:
        - name: increment-decrement
        - name: unused-parameter

  exclusions:
    presets:
      - comments
      - std-error-handling
    paths:
      - typescript-go
      - shim

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
