# yaml-language-server: $schema=https://golangci-lint.run/jsonschema/golangci.jsonschema.json

version: "2"

run:
  allow-parallel-runners: true

linters:
  default: none
  enable:
    - copyloopvar
    - bodyclose
    - bidichk
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - gocritic
    - gocheckcompilerdirectives
    - goprintffuncname
    - govet
    - ineffassign
    - intrange
    - makezero
    - mirror
    - misspell
    - modernize
    - musttag
    - nakedret
    - nolintlint
    - perfsprint
    - paralleltest
    - predeclared
    - reassign
    - revive
    - staticcheck
    - testableexamples
    - tparallel
    - unconvert
    - usestdlibvars
    - usetesting
    - durationcheck

  settings:
    paralleltest:
      ignore-missing-subtests: true
    revive:
      rules:
        - name: increment-decrement
        - name: unused-parameter

  exclusions:
    presets:
      - comments
      - std-error-handling
    paths:
      - typescript-go
      - shim

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
