
// Code generated by _tools/gen_shims. DO NOT EDIT.

package dirty

import "github.com/microsoft/TypeScript/tsc/internal/project/dirty"

type Box[T dirty.Cloneable[T]] = dirty.Box[T]
type Cloneable[T any] = dirty.Cloneable[T]
type CloneableMap[K comparable, V any] = dirty.CloneableMap[K,V]
type FinalizationHooks[K comparable, V any] = dirty.FinalizationHooks[K,V]
type Map[K comparable, V dirty.Cloneable[V]] = dirty.Map[K,V]
type MapBuilder[K comparable, VBase, VBuilder any] = dirty.MapBuilder[K,VBase,VBuilder]
type MapEntry[K comparable, V dirty.Cloneable[V]] = dirty.MapEntry[K,V]
type SyncMap[K comparable, V dirty.Cloneable[V]] = dirty.SyncMap[K,V]
type SyncMapEntry[K comparable, V dirty.Cloneable[V]] = dirty.SyncMapEntry[K,V]
type Value[T any] = dirty.Value[T]
