
// Code generated by _tools/gen_shims. DO NOT EDIT.

package change

import "context"
import "github.com/microsoft/TypeScript/tsc/internal/ast"
import "github.com/microsoft/TypeScript/tsc/internal/core"
import "github.com/microsoft/TypeScript/tsc/internal/ls/change"
import "github.com/microsoft/TypeScript/tsc/internal/ls/lsconv"
import "github.com/microsoft/TypeScript/tsc/internal/ls/lsutil"
import _ "unsafe"

//go:linkname GetFormatCodeSettingsForWriting github.com/microsoft/TypeScript/tsc/internal/ls/change.GetFormatCodeSettingsForWriting
func GetFormatCodeSettingsForWriting(options lsutil.FormatCodeSettings, sourceFile *ast.SourceFile) lsutil.FormatCodeSettings
type LeadingTriviaOption = change.LeadingTriviaOption
const LeadingTriviaOptionExclude = change.LeadingTriviaOptionExclude
const LeadingTriviaOptionIncludeAll = change.LeadingTriviaOptionIncludeAll
const LeadingTriviaOptionJSDoc = change.LeadingTriviaOptionJSDoc
const LeadingTriviaOptionNone = change.LeadingTriviaOptionNone
const LeadingTriviaOptionStartLine = change.LeadingTriviaOptionStartLine
//go:linkname NewTracker github.com/microsoft/TypeScript/tsc/internal/ls/change.NewTracker
func NewTracker(ctx context.Context, compilerOptions *core.CompilerOptions, formatOptions lsutil.FormatCodeSettings, converters *lsconv.Converters) *change.Tracker
type NodeOptions = change.NodeOptions
type Tracker = change.Tracker
//go:linkname Tracker_getNonformattedText github.com/microsoft/TypeScript/tsc/internal/ls/change.(*Tracker).getNonformattedText
func Tracker_getNonformattedText(recv *change.Tracker, node *ast.Node, sourceFile *ast.SourceFile) (string, *ast.Node)
type TrailingTriviaOption = change.TrailingTriviaOption
const TrailingTriviaOptionExclude = change.TrailingTriviaOptionExclude
const TrailingTriviaOptionExcludeWhitespace = change.TrailingTriviaOptionExcludeWhitespace
const TrailingTriviaOptionInclude = change.TrailingTriviaOptionInclude
const TrailingTriviaOptionNone = change.TrailingTriviaOptionNone
