
// Code generated by _tools/gen_shims. DO NOT EDIT.

package autoimport

import "context"
import "github.com/microsoft/TypeScript/tsc/internal/ast"
import "github.com/microsoft/TypeScript/tsc/internal/checker"
import "github.com/microsoft/TypeScript/tsc/internal/compiler"
import "github.com/microsoft/TypeScript/tsc/internal/ls/autoimport"
import "github.com/microsoft/TypeScript/tsc/internal/ls/lsconv"
import "github.com/microsoft/TypeScript/tsc/internal/ls/lsutil"
import "github.com/microsoft/TypeScript/tsc/internal/lsp/lsproto"
import "github.com/microsoft/TypeScript/tsc/internal/modulespecifiers"
import "github.com/microsoft/TypeScript/tsc/internal/tspath"
import _ "unsafe"

type BucketState = autoimport.BucketState
type BucketStats = autoimport.BucketStats
type CacheStats = autoimport.CacheStats
type Export = autoimport.Export
type ExportID = autoimport.ExportID
type ExportSyntax = autoimport.ExportSyntax
const ExportSyntaxCommonJSExportsProperty = autoimport.ExportSyntaxCommonJSExportsProperty
const ExportSyntaxCommonJSModuleExports = autoimport.ExportSyntaxCommonJSModuleExports
const ExportSyntaxDefaultDeclaration = autoimport.ExportSyntaxDefaultDeclaration
const ExportSyntaxDefaultModifier = autoimport.ExportSyntaxDefaultModifier
const ExportSyntaxEquals = autoimport.ExportSyntaxEquals
const ExportSyntaxModifier = autoimport.ExportSyntaxModifier
const ExportSyntaxNamed = autoimport.ExportSyntaxNamed
const ExportSyntaxNone = autoimport.ExportSyntaxNone
const ExportSyntaxStar = autoimport.ExportSyntaxStar
const ExportSyntaxUMD = autoimport.ExportSyntaxUMD
type Fix = autoimport.Fix
type FixAndExport = autoimport.FixAndExport
type FixTransformer = autoimport.FixTransformer
//go:linkname GetImportKindForImportStatement github.com/microsoft/TypeScript/tsc/internal/ls/autoimport.GetImportKindForImportStatement
func GetImportKindForImportStatement(importingFile *ast.SourceFile, export *autoimport.Export, program *compiler.Program) lsproto.ImportKind
type ImportAdder = autoimport.ImportAdder
type Index[T autoimport.Named] = autoimport.Index[T]
type ModuleID = autoimport.ModuleID
type Named = autoimport.Named
//go:linkname NewImportAdder github.com/microsoft/TypeScript/tsc/internal/ls/autoimport.NewImportAdder
func NewImportAdder(ctx context.Context, program *compiler.Program, checker *checker.Checker, file *ast.SourceFile, view *autoimport.View, formatOptions lsutil.FormatCodeSettings, converters *lsconv.Converters, preferences lsutil.UserPreferences) autoimport.ImportAdder
//go:linkname NewRegistry github.com/microsoft/TypeScript/tsc/internal/ls/autoimport.NewRegistry
func NewRegistry(toPath func(fileName string) tspath.Path, preferences lsutil.UserPreferences) *autoimport.Registry
//go:linkname NewView github.com/microsoft/TypeScript/tsc/internal/ls/autoimport.NewView
func NewView(registry *autoimport.Registry, importingFile *ast.SourceFile, projectKey tspath.Path, program *compiler.Program, preferences modulespecifiers.UserPreferences) *autoimport.View
type QueryKind = autoimport.QueryKind
const QueryKindCaseInsensitiveMatch = autoimport.QueryKindCaseInsensitiveMatch
const QueryKindExactMatch = autoimport.QueryKindExactMatch
const QueryKindWordPrefix = autoimport.QueryKindWordPrefix
//go:linkname RegisterAutoImportFixTransformer github.com/microsoft/TypeScript/tsc/internal/ls/autoimport.RegisterAutoImportFixTransformer
func RegisterAutoImportFixTransformer(factory func(prefs modulespecifiers.UserPreferences, program *compiler.Program, importingFile *ast.SourceFile) autoimport.FixTransformer)
type Registry = autoimport.Registry
type RegistryBucket = autoimport.RegistryBucket
type RegistryChange = autoimport.RegistryChange
type RegistryCloneHost = autoimport.RegistryCloneHost
//go:linkname SymbolToExport github.com/microsoft/TypeScript/tsc/internal/ls/autoimport.SymbolToExport
func SymbolToExport(symbol *ast.Symbol, ch *checker.Checker) *autoimport.Export
//go:linkname TryGetAutoImportableReferenceFromTypeNode github.com/microsoft/TypeScript/tsc/internal/ls/autoimport.TryGetAutoImportableReferenceFromTypeNode
func TryGetAutoImportableReferenceFromTypeNode(importTypeNode *ast.TypeNode, idToSymbol map[*ast.IdentifierNode]*ast.Symbol) (*ast.TypeNode, []*ast.Symbol)
//go:linkname TypeNodeToAutoImportableTypeNode github.com/microsoft/TypeScript/tsc/internal/ls/autoimport.TypeNodeToAutoImportableTypeNode
func TypeNodeToAutoImportableTypeNode(typeNode *ast.TypeNode, importAdder autoimport.ImportAdder, idToSymbol map[*ast.IdentifierNode]*ast.Symbol) *ast.TypeNode
//go:linkname TypeToAutoImportableTypeNode github.com/microsoft/TypeScript/tsc/internal/ls/autoimport.TypeToAutoImportableTypeNode
func TypeToAutoImportableTypeNode(c *checker.Checker, importAdder autoimport.ImportAdder, t *checker.Type, contextNode *ast.Node) *ast.TypeNode
type View = autoimport.View
