
// Code generated by _tools/gen_shims. DO NOT EDIT.

package baseline

import "github.com/microsoft/TypeScript/tsc/internal/testutil/baseline"
import "testing"
import _ "unsafe"

//go:linkname DiffText github.com/microsoft/TypeScript/tsc/internal/testutil/baseline.DiffText
func DiffText(oldName string, newName string, expected string, actual string) string
const NoContent = baseline.NoContent
type Options = baseline.Options
//go:linkname Run github.com/microsoft/TypeScript/tsc/internal/testutil/baseline.Run
func Run(t *testing.T, fileName string, actual string, opts baseline.Options)
//go:linkname Track github.com/microsoft/TypeScript/tsc/internal/testutil/baseline.Track
func Track() func()
