
// Code generated by _tools/gen_shims. DO NOT EDIT.

package tracing

import "github.com/microsoft/typescript-go/internal/tracing"
import "github.com/microsoft/typescript-go/internal/vfs"
import _ "unsafe"

type LineAndChar = tracing.LineAndChar
type Location = tracing.Location
type Phase = tracing.Phase
const PhaseBind = tracing.PhaseBind
const PhaseCheck = tracing.PhaseCheck
const PhaseCheckTypes = tracing.PhaseCheckTypes
const PhaseEmit = tracing.PhaseEmit
const PhaseParse = tracing.PhaseParse
const PhaseProgram = tracing.PhaseProgram
const PhaseSession = tracing.PhaseSession
//go:linkname StartTracing github.com/microsoft/typescript-go/internal/tracing.StartTracing
func StartTracing(fs vfs.FS, traceDir string, configFilePath string, deterministic bool) (*tracing.Tracing, error)
type TraceRecord = tracing.TraceRecord
type TracedType = tracing.TracedType
type Tracer = tracing.Tracer
type Tracing = tracing.Tracing
type TypeDescriptor = tracing.TypeDescriptor
