
// Code generated by _tools/gen_shims. DO NOT EDIT.

package vfsmatch

import "github.com/microsoft/TypeScript/tsc/internal/vfs/vfsmatch"
import _ "unsafe"

//go:linkname IsImplicitGlob github.com/microsoft/TypeScript/tsc/internal/vfs/vfsmatch.IsImplicitGlob
func IsImplicitGlob(lastPathComponent string) bool
type PathPatternInput = vfsmatch.PathPatternInput
type SpecMatcher = vfsmatch.SpecMatcher
const UnlimitedDepth = vfsmatch.UnlimitedDepth
type Usage = vfsmatch.Usage
const UsageDirectories = vfsmatch.UsageDirectories
const UsageExclude = vfsmatch.UsageExclude
const UsageFiles = vfsmatch.UsageFiles
