
// Code generated by _tools/gen_shims. DO NOT EDIT.

package printer

import "github.com/microsoft/TypeScript/tsc/internal/ast"
import "github.com/microsoft/TypeScript/tsc/internal/core"
import "github.com/microsoft/TypeScript/tsc/internal/printer"
import _ "unsafe"

var AdvancedAsyncSuperHelper = printer.AdvancedAsyncSuperHelper
type AssignedNameOptions = printer.AssignedNameOptions
var AsyncSuperHelper = printer.AsyncSuperHelper
type AutoGenerateId = printer.AutoGenerateId
type AutoGenerateInfo = printer.AutoGenerateInfo
type AutoGenerateOptions = printer.AutoGenerateOptions
type ChangeTrackerWriter = printer.ChangeTrackerWriter
//go:linkname CreateSyntheticSourceFile github.com/microsoft/TypeScript/tsc/internal/printer.CreateSyntheticSourceFile
func CreateSyntheticSourceFile(factory *ast.NodeFactory, node *ast.Node, text string, parseOptions ast.SourceFileParseOptions) *ast.SourceFile
const EFAsyncFunctionBody = printer.EFAsyncFunctionBody
const EFCustomPrologue = printer.EFCustomPrologue
const EFExportName = printer.EFExportName
const EFExternalHelpers = printer.EFExternalHelpers
const EFHelperName = printer.EFHelperName
const EFIndented = printer.EFIndented
const EFIndirectCall = printer.EFIndirectCall
const EFLocalName = printer.EFLocalName
const EFMultiLine = printer.EFMultiLine
const EFNoAsciiEscaping = printer.EFNoAsciiEscaping
const EFNoComments = printer.EFNoComments
const EFNoIndentation = printer.EFNoIndentation
const EFNoLeadingComments = printer.EFNoLeadingComments
const EFNoLeadingSourceMap = printer.EFNoLeadingSourceMap
const EFNoLexicalArguments = printer.EFNoLexicalArguments
const EFNoLexicalThis = printer.EFNoLexicalThis
const EFNoNestedComments = printer.EFNoNestedComments
const EFNoNestedSourceMaps = printer.EFNoNestedSourceMaps
const EFNoSourceMap = printer.EFNoSourceMap
const EFNoTokenLeadingSourceMaps = printer.EFNoTokenLeadingSourceMaps
const EFNoTokenSourceMaps = printer.EFNoTokenSourceMaps
const EFNoTokenTrailingSourceMaps = printer.EFNoTokenTrailingSourceMaps
const EFNoTrailingComments = printer.EFNoTrailingComments
const EFNoTrailingSourceMap = printer.EFNoTrailingSourceMap
const EFNone = printer.EFNone
const EFReuseTempVariableScope = printer.EFReuseTempVariableScope
const EFSingleLine = printer.EFSingleLine
const EFStartOnNewLine = printer.EFStartOnNewLine
const EFTransformPrivateStaticElements = printer.EFTransformPrivateStaticElements
type EmitContext = printer.EmitContext
type EmitFlags = printer.EmitFlags
type EmitHelper = printer.EmitHelper
type EmitHost = printer.EmitHost
type EmitResolver = printer.EmitResolver
type EmitTextWriter = printer.EmitTextWriter
//go:linkname EscapeString github.com/microsoft/TypeScript/tsc/internal/printer.EscapeString
func EscapeString(s string, quoteChar printer.QuoteChar) string
//go:linkname FormatGeneratedName github.com/microsoft/TypeScript/tsc/internal/printer.FormatGeneratedName
func FormatGeneratedName(privateName bool, prefix string, base string, suffix string) string
type GeneratedIdentifierFlags = printer.GeneratedIdentifierFlags
const GeneratedIdentifierFlagsAllowNameSubstitution = printer.GeneratedIdentifierFlagsAllowNameSubstitution
const GeneratedIdentifierFlagsAuto = printer.GeneratedIdentifierFlagsAuto
const GeneratedIdentifierFlagsFileLevel = printer.GeneratedIdentifierFlagsFileLevel
const GeneratedIdentifierFlagsKindMask = printer.GeneratedIdentifierFlagsKindMask
const GeneratedIdentifierFlagsLoop = printer.GeneratedIdentifierFlagsLoop
const GeneratedIdentifierFlagsNode = printer.GeneratedIdentifierFlagsNode
const GeneratedIdentifierFlagsNone = printer.GeneratedIdentifierFlagsNone
const GeneratedIdentifierFlagsOptimistic = printer.GeneratedIdentifierFlagsOptimistic
const GeneratedIdentifierFlagsReservedInNestedScopes = printer.GeneratedIdentifierFlagsReservedInNestedScopes
const GeneratedIdentifierFlagsUnique = printer.GeneratedIdentifierFlagsUnique
//go:linkname GetDefaultIndentSize github.com/microsoft/TypeScript/tsc/internal/printer.GetDefaultIndentSize
func GetDefaultIndentSize() int
//go:linkname GetEmitContext github.com/microsoft/TypeScript/tsc/internal/printer.GetEmitContext
func GetEmitContext() (*printer.EmitContext, func())
//go:linkname GetLinesBetweenPositions github.com/microsoft/TypeScript/tsc/internal/printer.GetLinesBetweenPositions
func GetLinesBetweenPositions(sourceFile *ast.SourceFile, pos1 int, pos2 int) int
//go:linkname GetSingleLineStringWriter github.com/microsoft/TypeScript/tsc/internal/printer.GetSingleLineStringWriter
func GetSingleLineStringWriter() (printer.EmitTextWriter, func())
//go:linkname IsPinnedComment github.com/microsoft/TypeScript/tsc/internal/printer.IsPinnedComment
func IsPinnedComment(text string, comment ast.CommentRange) bool
//go:linkname IsRecognizedTripleSlashComment github.com/microsoft/TypeScript/tsc/internal/printer.IsRecognizedTripleSlashComment
func IsRecognizedTripleSlashComment(text string, commentRange ast.CommentRange) bool
const LFAllowTrailingComma = printer.LFAllowTrailingComma
const LFAmpersandDelimited = printer.LFAmpersandDelimited
const LFAngleBrackets = printer.LFAngleBrackets
const LFArrayBindingPatternElements = printer.LFArrayBindingPatternElements
const LFArrayLiteralExpressionElements = printer.LFArrayLiteralExpressionElements
const LFAsteriskDelimited = printer.LFAsteriskDelimited
const LFBarDelimited = printer.LFBarDelimited
const LFBraces = printer.LFBraces
const LFBracketsMask = printer.LFBracketsMask
const LFCallExpressionArguments = printer.LFCallExpressionArguments
const LFCaseBlockClauses = printer.LFCaseBlockClauses
const LFCaseOrDefaultClauseStatements = printer.LFCaseOrDefaultClauseStatements
const LFClassHeritageClauses = printer.LFClassHeritageClauses
const LFClassMembers = printer.LFClassMembers
const LFCommaDelimited = printer.LFCommaDelimited
const LFCommaListElements = printer.LFCommaListElements
const LFDecorators = printer.LFDecorators
const LFDelimitersMask = printer.LFDelimitersMask
const LFEnumMembers = printer.LFEnumMembers
const LFHeritageClauseTypes = printer.LFHeritageClauseTypes
const LFHeritageClauses = printer.LFHeritageClauses
const LFImportAttributes = printer.LFImportAttributes
const LFImportClauseEntries = printer.LFImportClauseEntries
const LFIndented = printer.LFIndented
const LFIndexSignatureParameters = printer.LFIndexSignatureParameters
const LFInterfaceMembers = printer.LFInterfaceMembers
const LFIntersectionTypeConstituents = printer.LFIntersectionTypeConstituents
const LFJSDocComment = printer.LFJSDocComment
const LFJsxElementAttributes = printer.LFJsxElementAttributes
const LFJsxElementOrFragmentChildren = printer.LFJsxElementOrFragmentChildren
const LFLinesMask = printer.LFLinesMask
const LFModifiers = printer.LFModifiers
const LFMultiLine = printer.LFMultiLine
const LFMultiLineBlockStatements = printer.LFMultiLineBlockStatements
const LFMultiLineFunctionBodyStatements = printer.LFMultiLineFunctionBodyStatements
const LFMultiLineTupleTypeElements = printer.LFMultiLineTupleTypeElements
const LFMultiLineTypeLiteralMembers = printer.LFMultiLineTypeLiteralMembers
const LFNamedImportsOrExportsElements = printer.LFNamedImportsOrExportsElements
const LFNewExpressionArguments = printer.LFNewExpressionArguments
const LFNoInterveningComments = printer.LFNoInterveningComments
const LFNoSpaceIfEmpty = printer.LFNoSpaceIfEmpty
const LFNoTrailingNewLine = printer.LFNoTrailingNewLine
const LFNone = printer.LFNone
const LFNotDelimited = printer.LFNotDelimited
const LFObjectBindingPatternElements = printer.LFObjectBindingPatternElements
const LFObjectLiteralExpressionProperties = printer.LFObjectLiteralExpressionProperties
const LFOptional = printer.LFOptional
const LFOptionalIfEmpty = printer.LFOptionalIfEmpty
const LFOptionalIfNil = printer.LFOptionalIfNil
const LFParameters = printer.LFParameters
const LFParenthesis = printer.LFParenthesis
const LFPreferNewLine = printer.LFPreferNewLine
const LFPreserveLines = printer.LFPreserveLines
const LFSingleArrowParameter = printer.LFSingleArrowParameter
const LFSingleElement = printer.LFSingleElement
const LFSingleLine = printer.LFSingleLine
const LFSingleLineBlockStatements = printer.LFSingleLineBlockStatements
const LFSingleLineFunctionBodyStatements = printer.LFSingleLineFunctionBodyStatements
const LFSingleLineTupleTypeElements = printer.LFSingleLineTupleTypeElements
const LFSingleLineTypeLiteralMembers = printer.LFSingleLineTypeLiteralMembers
const LFSourceFileStatements = printer.LFSourceFileStatements
const LFSpaceAfterList = printer.LFSpaceAfterList
const LFSpaceBetweenBraces = printer.LFSpaceBetweenBraces
const LFSpaceBetweenSiblings = printer.LFSpaceBetweenSiblings
const LFSquareBrackets = printer.LFSquareBrackets
const LFTemplateExpressionSpans = printer.LFTemplateExpressionSpans
const LFTypeArguments = printer.LFTypeArguments
const LFTypeParameters = printer.LFTypeParameters
const LFUnionTypeConstituents = printer.LFUnionTypeConstituents
const LFVariableDeclarationList = printer.LFVariableDeclarationList
type ListFormat = printer.ListFormat
type NameGenerator = printer.NameGenerator
type NameOptions = printer.NameOptions
//go:linkname NewChangeTrackerWriter github.com/microsoft/TypeScript/tsc/internal/printer.NewChangeTrackerWriter
func NewChangeTrackerWriter(newline string, indentSize int) *printer.ChangeTrackerWriter
//go:linkname NewEmitContext github.com/microsoft/TypeScript/tsc/internal/printer.NewEmitContext
func NewEmitContext() *printer.EmitContext
//go:linkname NewNodeFactory github.com/microsoft/TypeScript/tsc/internal/printer.NewNodeFactory
func NewNodeFactory(context *printer.EmitContext) *printer.NodeFactory
//go:linkname NewPrinter github.com/microsoft/TypeScript/tsc/internal/printer.NewPrinter
func NewPrinter(options printer.PrinterOptions, handlers printer.PrintHandlers, emitContext *printer.EmitContext) *printer.Printer
//go:linkname NewTextWriter github.com/microsoft/TypeScript/tsc/internal/printer.NewTextWriter
func NewTextWriter(newLine string, indentSize int) printer.EmitTextWriter
type NodeFactory = printer.NodeFactory
//go:linkname PositionsAreOnSameLine github.com/microsoft/TypeScript/tsc/internal/printer.PositionsAreOnSameLine
func PositionsAreOnSameLine(pos1 int, pos2 int, sourceFile *ast.SourceFile) bool
//go:linkname PrintAndPositionNode github.com/microsoft/TypeScript/tsc/internal/printer.PrintAndPositionNode
func PrintAndPositionNode(factory *ast.NodeFactory, node *ast.Node, sourceFile *ast.SourceFile, newLine string, indentSize int, emitContext *printer.EmitContext) (text string, positioned *ast.Node)
type PrintHandlers = printer.PrintHandlers
type Printer = printer.Printer
type PrinterOptions = printer.PrinterOptions
type Priority = printer.Priority
type PrivateIdentifierKind = printer.PrivateIdentifierKind
const PrivateIdentifierKindAccessor = printer.PrivateIdentifierKindAccessor
const PrivateIdentifierKindField = printer.PrivateIdentifierKindField
const PrivateIdentifierKindMethod = printer.PrivateIdentifierKindMethod
const PrivateIdentifierKindUntransformed = printer.PrivateIdentifierKindUntransformed
type QuoteChar = printer.QuoteChar
const QuoteCharBacktick = printer.QuoteCharBacktick
const QuoteCharDoubleQuote = printer.QuoteCharDoubleQuote
const QuoteCharSingleQuote = printer.QuoteCharSingleQuote
//go:linkname RangeIsOnSingleLine github.com/microsoft/TypeScript/tsc/internal/printer.RangeIsOnSingleLine
func RangeIsOnSingleLine(r core.TextRange, sourceFile *ast.SourceFile) bool
//go:linkname RangeStartPositionsAreOnSameLine github.com/microsoft/TypeScript/tsc/internal/printer.RangeStartPositionsAreOnSameLine
func RangeStartPositionsAreOnSameLine(range1 core.TextRange, range2 core.TextRange, sourceFile *ast.SourceFile) bool
type SnippetElement = printer.SnippetElement
type SnippetKind = printer.SnippetKind
const SnippetKindTabStop = printer.SnippetKindTabStop
type SourceFileMetaDataProvider = printer.SourceFileMetaDataProvider
type SymbolAccessibility = printer.SymbolAccessibility
const SymbolAccessibilityAccessible = printer.SymbolAccessibilityAccessible
const SymbolAccessibilityCannotBeNamed = printer.SymbolAccessibilityCannotBeNamed
const SymbolAccessibilityNotAccessible = printer.SymbolAccessibilityNotAccessible
const SymbolAccessibilityNotResolved = printer.SymbolAccessibilityNotResolved
type SymbolAccessibilityResult = printer.SymbolAccessibilityResult
type SynthesizedComment = printer.SynthesizedComment
type TypeReferenceSerializationKind = printer.TypeReferenceSerializationKind
const TypeReferenceSerializationKindArrayLikeType = printer.TypeReferenceSerializationKindArrayLikeType
const TypeReferenceSerializationKindBigIntLikeType = printer.TypeReferenceSerializationKindBigIntLikeType
const TypeReferenceSerializationKindBooleanType = printer.TypeReferenceSerializationKindBooleanType
const TypeReferenceSerializationKindESSymbolType = printer.TypeReferenceSerializationKindESSymbolType
const TypeReferenceSerializationKindNumberLikeType = printer.TypeReferenceSerializationKindNumberLikeType
const TypeReferenceSerializationKindObjectType = printer.TypeReferenceSerializationKindObjectType
const TypeReferenceSerializationKindPromise = printer.TypeReferenceSerializationKindPromise
const TypeReferenceSerializationKindStringLikeType = printer.TypeReferenceSerializationKindStringLikeType
const TypeReferenceSerializationKindTypeWithCallSignature = printer.TypeReferenceSerializationKindTypeWithCallSignature
const TypeReferenceSerializationKindTypeWithConstructSignatureAndValue = printer.TypeReferenceSerializationKindTypeWithConstructSignatureAndValue
const TypeReferenceSerializationKindUnknown = printer.TypeReferenceSerializationKindUnknown
const TypeReferenceSerializationKindVoidNullableOrNeverType = printer.TypeReferenceSerializationKindVoidNullableOrNeverType
type WriteKind = printer.WriteKind
const WriteKindComment = printer.WriteKindComment
const WriteKindKeyword = printer.WriteKindKeyword
const WriteKindLiteral = printer.WriteKindLiteral
const WriteKindNone = printer.WriteKindNone
const WriteKindOperator = printer.WriteKindOperator
const WriteKindParameter = printer.WriteKindParameter
const WriteKindProperty = printer.WriteKindProperty
const WriteKindPunctuation = printer.WriteKindPunctuation
const WriteKindStringLiteral = printer.WriteKindStringLiteral
