import * as NodeServices from "@effect/platform-node/NodeServices"
import * as Effect from "effect/Effect"
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import assert from "node:assert/strict"
import test from "node:test"
import { addChangeset, writeGeneratedVersion } from "../src/changesets.ts"

test("generates the Go version from the CLI package", async() => {
  const repository = mkdtempSync(join(tmpdir(), "repoctl-version-"))

  try {
    mkdirSync(join(repository, "_packages", "tsgo"), { recursive: true })
    mkdirSync(join(repository, "etscore"))
    writeFileSync(join(repository, "_packages", "tsgo", "package.json"), JSON.stringify({ version: "1.2.3" }))

    await Effect.runPromise(
      writeGeneratedVersion(repository).pipe(Effect.provide(NodeServices.layer))
    )

    assert.equal(readFileSync(join(repository, "etscore", "version_generated.go"), "utf8"), [
      "// Code generated by repoctl changeset version. DO NOT EDIT.",
      "",
      "package etscore",
      "",
      "const EffectVersion = \"1.2.3\"",
      ""
    ].join("\n"))
  } finally {
    rmSync(repository, { recursive: true, force: true })
  }
})

test("adds a changeset", async() => {
  const repository = mkdtempSync(join(tmpdir(), "repoctl-changeset-"))

  try {
    mkdirSync(join(repository, ".changeset"))

    await Effect.runPromise(
      addChangeset(repository, "update-upstream", "@effect/tsgo", "patch", "Update upstream metadata.").pipe(
        Effect.provide(NodeServices.layer)
      )
    )

    assert.equal(readFileSync(join(repository, ".changeset", "update-upstream.md"), "utf8"), [
      "---",
      "\"@effect/tsgo\": patch",
      "---",
      "",
      "Update upstream metadata.",
      ""
    ].join("\n"))
  } finally {
    rmSync(repository, { recursive: true, force: true })
  }
})
