import assert from "node:assert/strict"
import test from "node:test"
import {
  OxlintCodegenError,
  renderOxlintEffectRules,
  TsgolintCodegenError,
  renderTsgolintEffectRules
} from "../src/codegen.ts"

test("generates sorted native tsgolint Effect rules", () => {
  const output = renderTsgolintEffectRules({
    rules: [
      { name: "globalFetchInEffect" },
      { name: "anyUnknownInErrorContext" }
    ]
  })

  assert.match(output, /Code generated by repoctl codegen tsgolint/)
  assert.ok(output.indexOf('newEffectRule("effect/any-unknown-in-error-context"') <
    output.indexOf('newEffectRule("effect/global-fetch-in-effect"'))
  assert.match(output, /etsrulerunner\.RunRule/)
  assert.match(output, /return nil/)
})

test("rejects colliding generated rule names", () => {
  assert.throws(
    () => renderTsgolintEffectRules({ rules: [{ name: "fooBAR" }, { name: "fooBar" }] }),
    (error) => error instanceof TsgolintCodegenError && error.reason === "duplicate tsgolint rule name effect/foo-bar"
  )
})

test("generates sorted metadata-only Oxlint rules", () => {
  const output = renderOxlintEffectRules({
    rules: [
      { name: "globalFetchInEffect", description: "Detects global fetch", fixable: false },
      { name: "cryptoRandomUUID", description: "Detects random UUID usage", fixable: true }
    ]
  })

  assert.deepEqual(output.rules.map(({ moduleName }) => moduleName), ["crypto_random_uuid", "global_fetch_in_effect"])
  assert.match(output.moduleBlock, /pub\(crate\) mod effect/)
  assert.match(output.moduleBlock, /pub mod crypto_random_uuid;/)
  assert.match(output.rules[0]!.source, /pub struct CryptoRandomUuid;/)
  assert.match(output.rules[0]!.source, /CryptoRandomUuid\(tsgolint\)/)
  assert.match(output.rules[0]!.source, /pending,/)
  assert.match(output.rules[0]!.source, /version = "next",/)
  assert.match(output.rules[1]!.source, /none,/)
})

test("rejects Oxlint rules without descriptions", () => {
  assert.throws(
    () => renderOxlintEffectRules({ rules: [{ name: "floatingEffect" }] }),
    (error) => error instanceof OxlintCodegenError && error.reason === "metadata.rules[0].description is invalid"
  )
})
