
// Code generated by _tools/gen_shims. DO NOT EDIT.

package lsconv

import "context"
import "github.com/microsoft/TypeScript/tsc/internal/ast"
import "github.com/microsoft/TypeScript/tsc/internal/core"
import "github.com/microsoft/TypeScript/tsc/internal/ls/lsconv"
import "github.com/microsoft/TypeScript/tsc/internal/lsp/lsproto"
import _ "unsafe"

//go:linkname ComputeLSPLineStarts github.com/microsoft/TypeScript/tsc/internal/ls/lsconv.ComputeLSPLineStarts
func ComputeLSPLineStarts(text string) *lsconv.LSPLineMap
type Converters = lsconv.Converters
//go:linkname DiagnosticToLSPPull github.com/microsoft/TypeScript/tsc/internal/ls/lsconv.DiagnosticToLSPPull
func DiagnosticToLSPPull(ctx context.Context, converters *lsconv.Converters, diagnostic *ast.Diagnostic, reportStyleChecksAsWarnings bool) *lsproto.Diagnostic
//go:linkname DiagnosticToLSPPush github.com/microsoft/TypeScript/tsc/internal/ls/lsconv.DiagnosticToLSPPush
func DiagnosticToLSPPush(ctx context.Context, converters *lsconv.Converters, diagnostic *ast.Diagnostic) *lsproto.Diagnostic
//go:linkname FileNameToDocumentURI github.com/microsoft/TypeScript/tsc/internal/ls/lsconv.FileNameToDocumentURI
func FileNameToDocumentURI(fileName string) lsproto.DocumentUri
type LSPLineMap = lsconv.LSPLineMap
type LSPLineStarts = lsconv.LSPLineStarts
//go:linkname LanguageKindToScriptKind github.com/microsoft/TypeScript/tsc/internal/ls/lsconv.LanguageKindToScriptKind
func LanguageKindToScriptKind(languageID lsproto.LanguageKind) core.ScriptKind
type MappedPosition[T lsconv.Script] = lsconv.MappedPosition[T]
type MappedSpan[T lsconv.Script] = lsconv.MappedSpan[T]
//go:linkname NewConverters github.com/microsoft/TypeScript/tsc/internal/ls/lsconv.NewConverters
func NewConverters(positionEncoding lsproto.PositionEncodingKind, getLineMap func(fileName string) *lsconv.LSPLineMap) *lsconv.Converters
type Script = lsconv.Script
