import * as Console from "effect/Console"
import * as Data from "effect/Data"
import * as Effect from "effect/Effect"
import * as FileSystem from "effect/FileSystem"
import * as Path from "effect/Path"
import { generateTsgolintWorkspace } from "./oxlint.ts"
import { runCommand } from "./process.ts"
import { generateSubmoduleArtifacts } from "./submodules.ts"
import type { TypeScriptSource } from "./upstream.ts"

interface RuleMetadata {
  readonly description?: unknown
  readonly fixable?: unknown
  readonly group?: unknown
  readonly name?: unknown
}

interface Metadata {
  readonly rules?: unknown
}

export class TsgolintCodegenError extends Data.TaggedError("TsgolintCodegenError")<{
  readonly reason: string
}> {
  get message(): string {
    return `Unable to generate tsgolint Effect rules: ${this.reason}`
  }
}

export class OxlintCodegenError extends Data.TaggedError("OxlintCodegenError")<{
  readonly reason: string
}> {
  get message(): string {
    return `Unable to generate Oxlint Effect rules: ${this.reason}`
  }
}

const toKebabCase = (value: string): string => {
  let result = ""
  const characters = [...value]
  for (let index = 0; index < characters.length; index++) {
    const current = characters[index]!
    if (current >= "A" && current <= "Z") {
      const previous = characters[index - 1]
      const next = characters[index + 1]
      const previousIsLower = previous !== undefined && previous >= "a" && previous <= "z"
      const nextIsLower = next !== undefined && next >= "a" && next <= "z"
      if (index > 0 && (previousIsLower || nextIsLower)) result += "-"
      result += current.toLowerCase()
    } else {
      result += current
    }
  }
  return result
}

export const renderTsgolintEffectRules = (metadata: Metadata): string => {
  if (!Array.isArray(metadata.rules)) {
    throw new TsgolintCodegenError({ reason: "metadata.rules must be an array" })
  }

  const seenEffectNames = new Set<string>()
  const seenQualifiedNames = new Set<string>()
  const rules = (metadata.rules as ReadonlyArray<RuleMetadata>).map((rule, index) => {
    if (typeof rule !== "object" || rule === null ||
      typeof rule.name !== "string" || !/^[a-z][A-Za-z0-9]*$/.test(rule.name)) {
      throw new TsgolintCodegenError({ reason: `metadata.rules[${index}].name is invalid` })
    }
    if (seenEffectNames.has(rule.name)) {
      throw new TsgolintCodegenError({ reason: `duplicate Effect rule name ${rule.name}` })
    }
    seenEffectNames.add(rule.name)

    const qualifiedName = `effecttsgo/${toKebabCase(rule.name)}`
    if (seenQualifiedNames.has(qualifiedName)) {
      throw new TsgolintCodegenError({ reason: `duplicate tsgolint rule name ${qualifiedName}` })
    }
    seenQualifiedNames.add(qualifiedName)
    return { effectName: rule.name, qualifiedName }
  }).sort((left, right) => left.qualifiedName < right.qualifiedName ? -1 : left.qualifiedName > right.qualifiedName ? 1 : 0)

  const registrations = rules
    .map(({ effectName, qualifiedName }) => `\tnewEffectRule(${JSON.stringify(qualifiedName)}, ${JSON.stringify(effectName)}),`)
    .join("\n")

  return `// Code generated by repoctl codegen tsgolint. DO NOT EDIT.

package main

import (
\t"context"
\t"fmt"

\t"github.com/effect-ts/tsgo/etsoxlintrunner"
\t"github.com/typescript-eslint/tsgolint/internal/rule"
\t"github.com/typescript-eslint/tsgolint/internal/utils"
)

var effectRules = []rule.Rule{
${registrations}
}

func newEffectRule(name string, effectName string) rule.Rule {
\treturn rule.Rule{
\t\tName: name,
\t\tRun: func(ctx rule.RuleContext, _ any) rule.RuleListeners {
\t\t\terr := etsoxlintrunner.RunRuleAndReport(
\t\t\t\tcontext.Background(),
\t\t\t\tctx.Program,
\t\t\t\tctx.TypeChecker,
\t\t\t\tctx.SourceFile,
\t\t\t\tctx.Program.Options().Effect,
\t\t\t\teffectName,
\t\t\t\tetsoxlintrunner.DiagnosticAdapter{
\t\t\t\t\tMessage: utils.GetDiagnosticMessage,
\t\t\t\t\tReport: func(diagnostic etsoxlintrunner.ReportedDiagnostic) {
\t\t\t\t\t\tlabeledRanges := make([]rule.RuleLabeledRange, 0, len(diagnostic.RelatedInformation))
\t\t\t\t\t\tfor _, related := range diagnostic.RelatedInformation {
\t\t\t\t\t\t\tif related.FileName == ctx.SourceFile.FileName() {
\t\t\t\t\t\t\t\tlabeledRanges = append(labeledRanges, rule.RuleLabeledRange{
\t\t\t\t\t\t\t\t\tLabel: related.Description,
\t\t\t\t\t\t\t\t\tRange: related.Range,
\t\t\t\t\t\t\t\t})
\t\t\t\t\t\t\t}
\t\t\t\t\t\t}
\t\t\t\t\t\truleDiagnostic := rule.RuleDiagnostic{
\t\t\t\t\t\t\tRange:         diagnostic.Range,
\t\t\t\t\t\t\tRuleName:      name,
\t\t\t\t\t\t\tLabeledRanges: labeledRanges,
\t\t\t\t\t\t\tMessage: rule.RuleMessage{
\t\t\t\t\t\t\t\tId:          diagnostic.MessageID,
\t\t\t\t\t\t\t\tDescription: diagnostic.Description,
\t\t\t\t\t\t\t},
\t\t\t\t\t\t}
\t\t\t\t\t\tctx.ReportDiagnosticWithSuggestions(ruleDiagnostic, func() []rule.RuleSuggestion {
\t\t\t\t\t\t\treported := diagnostic.Suggestions()
\t\t\t\t\t\t\tsuggestions := make([]rule.RuleSuggestion, 0, len(reported))
\t\t\t\t\t\t\tfor _, suggestion := range reported {
\t\t\t\t\t\t\t\tfixes := make([]rule.RuleFix, 0, len(suggestion.Edits))
\t\t\t\t\t\t\t\tfor _, edit := range suggestion.Edits {
\t\t\t\t\t\t\t\t\tfixes = append(fixes, rule.RuleFix{Range: edit.Range, Text: edit.Text})
\t\t\t\t\t\t\t\t}
\t\t\t\t\t\t\t\tsuggestions = append(suggestions, rule.RuleSuggestion{
\t\t\t\t\t\t\t\t\tMessage: rule.RuleMessage{Description: suggestion.Description},
\t\t\t\t\t\t\t\t\tFixesArr: fixes,
\t\t\t\t\t\t\t\t})
\t\t\t\t\t\t\t}
\t\t\t\t\t\t\treturn suggestions
\t\t\t\t\t\t})
\t\t\t\t\t},
\t\t\t\t},
\t\t\t)
\t\t\tif err != nil {
\t\t\t\tpanic(fmt.Sprintf("running %s: %v", name, err))
\t\t\t}
\t\t\treturn nil
\t\t},
\t}
}
`
}

export interface OxlintEffectRuleSource {
  readonly moduleName: string
  readonly source: string
}

export interface OxlintEffectRulesSource {
  readonly moduleBlock: string
  readonly rules: ReadonlyArray<OxlintEffectRuleSource>
}

const effectRulesStart = "// BEGIN GENERATED EFFECT RULES"
const effectRulesEnd = "// END GENERATED EFFECT RULES"

const oxlintCategoryByEffectGroup = new Map([
  ["correctness", "correctness"],
  ["antipattern", "suspicious"],
  ["effectNative", "restriction"],
  ["style", "style"]
])

export const renderOxlintEffectRules = (metadata: Metadata): OxlintEffectRulesSource => {
  if (!Array.isArray(metadata.rules)) {
    throw new OxlintCodegenError({ reason: "metadata.rules must be an array" })
  }

  const seenEffectNames = new Set<string>()
  const seenModuleNames = new Set<string>()
  const rules = (metadata.rules as ReadonlyArray<RuleMetadata>).map((rule, index) => {
    if (typeof rule !== "object" || rule === null ||
      typeof rule.name !== "string" || !/^[a-z][A-Za-z0-9]*$/.test(rule.name)) {
      throw new OxlintCodegenError({ reason: `metadata.rules[${index}].name is invalid` })
    }
    if (typeof rule.description !== "string" || rule.description.length === 0) {
      throw new OxlintCodegenError({ reason: `metadata.rules[${index}].description is invalid` })
    }
    if (typeof rule.fixable !== "boolean") {
      throw new OxlintCodegenError({ reason: `metadata.rules[${index}].fixable is invalid` })
    }
    const category = typeof rule.group === "string" ? oxlintCategoryByEffectGroup.get(rule.group) : undefined
    if (category === undefined) {
      throw new OxlintCodegenError({ reason: `metadata.rules[${index}].group is invalid` })
    }
    if (seenEffectNames.has(rule.name)) {
      throw new OxlintCodegenError({ reason: `duplicate Effect rule name ${rule.name}` })
    }
    seenEffectNames.add(rule.name)

    const qualifiedName = `effecttsgo/${toKebabCase(rule.name)}`
    const moduleName = qualifiedName.slice("effecttsgo/".length).replaceAll("-", "_")
    if (seenModuleNames.has(moduleName)) {
      throw new OxlintCodegenError({ reason: `duplicate Oxlint rule module ${moduleName}` })
    }
    seenModuleNames.add(moduleName)
    const structName = moduleName.split("_")
      .map((part) => `${part[0]!.toUpperCase()}${part.slice(1)}`)
      .join("")
    const description = rule.description.replaceAll("\n", " ")
    const fix = rule.fixable ? "pending" : "none"

    return {
      moduleName,
      source: `// Code generated by repoctl codegen oxlint. DO NOT EDIT.

use oxc_macros::declare_oxc_lint;

use crate::rule::Rule;

#[derive(Debug, Default, Clone)]
pub struct ${structName};

declare_oxc_lint!(
    /// ${description}
    ${structName}(tsgolint),
    effecttsgo,
    ${category},
    ${fix},
    version = "next",
);

impl Rule for ${structName} {}
`
    }
  }).sort((left, right) => left.moduleName < right.moduleName ? -1 : left.moduleName > right.moduleName ? 1 : 0)

  return {
    moduleBlock: `${effectRulesStart}
pub(crate) mod effecttsgo {
${rules.map(({ moduleName }) => `    pub mod ${moduleName};`).join("\n")}
}
${effectRulesEnd}`,
    rules
  }
}

export const generateTsgolintEffectRules = Effect.fnUntraced(function*(repositoryRoot: string) {
  const fs = yield* FileSystem.FileSystem
  const path = yield* Path.Path
  const metadataPath = path.join(repositoryRoot, "_packages", "tsgo", "src", "metadata.json")
  const outputPath = path.join(repositoryRoot, "tsgolint", "cmd", "tsgolint", "effect_rules_generated.go")
  if (!(yield* fs.exists(path.dirname(outputPath)))) {
    return yield* new TsgolintCodegenError({ reason: "tsgolint checkout is not materialized" })
  }

  const metadataText = yield* fs.readFileString(metadataPath)
  const metadata = yield* Effect.try({
    try: () => JSON.parse(metadataText) as Metadata,
    catch: (error) => new TsgolintCodegenError({ reason: `unable to parse ${metadataPath}: ${String(error)}` })
  })
  yield* fs.writeFileString(outputPath, renderTsgolintEffectRules(metadata))
  yield* Console.log(`Generated tsgolint Effect rules: ${path.relative(repositoryRoot, outputPath)}`)
})

export const generateTsgolintIntegration = Effect.fnUntraced(function*(
  repositoryRoot: string,
  compiler: TypeScriptSource
) {
  yield* generateTsgolintWorkspace(repositoryRoot, compiler)
  yield* generateTsgolintEffectRules(repositoryRoot)
})

export const generateTypeScriptGoIntegration = Effect.fnUntraced(function*(
  repositoryRoot: string,
  compiler: TypeScriptSource
) {
  yield* generateSubmoduleArtifacts(repositoryRoot, compiler)
})

export const generateOxlintEffectRules = Effect.fnUntraced(function*(repositoryRoot: string) {
  const fs = yield* FileSystem.FileSystem
  const path = yield* Path.Path
  const oxlint = path.join(repositoryRoot, "oxlint")
  const metadataPath = path.join(repositoryRoot, "_packages", "tsgo", "src", "metadata.json")
  const rulesFile = path.join(oxlint, "crates", "oxc_linter", "src", "rules.rs")
  if (!(yield* fs.exists(rulesFile))) {
    return yield* new OxlintCodegenError({ reason: "Oxlint checkout is not materialized" })
  }

  const metadataText = yield* fs.readFileString(metadataPath)
  const metadata = yield* Effect.try({
    try: () => JSON.parse(metadataText) as Metadata,
    catch: (error) => new OxlintCodegenError({ reason: `unable to parse ${metadataPath}: ${String(error)}` })
  })
  const generated = renderOxlintEffectRules(metadata)
  const rulesSource = yield* fs.readFileString(rulesFile)
  const start = rulesSource.indexOf(effectRulesStart)
  const end = rulesSource.indexOf(effectRulesEnd, start)
  if (start === -1 || end === -1) {
    return yield* new OxlintCodegenError({ reason: `${rulesFile} does not contain Effect rule markers` })
  }

  const rulesDirectory = path.join(oxlint, "crates", "oxc_linter", "src", "rules", "effecttsgo")
  yield* fs.remove(rulesDirectory, { recursive: true, force: true })
  yield* fs.makeDirectory(rulesDirectory, { recursive: true })
  for (const rule of generated.rules) {
    yield* fs.writeFileString(path.join(rulesDirectory, `${rule.moduleName}.rs`), rule.source)
  }

  yield* fs.writeFileString(
    rulesFile,
    `${rulesSource.slice(0, start)}${generated.moduleBlock}${rulesSource.slice(end + effectRulesEnd.length)}`
  )
  yield* runCommand("cargo", oxlint, ["lintgen"])
  yield* Console.log(`Generated ${generated.rules.length} Oxlint Effect rules`)
})
