
// Code generated by _tools/gen_shims. DO NOT EDIT.

package packagejson

import "github.com/microsoft/TypeScript/tsc/internal/packagejson"
import _ "unsafe"

type ContentMapperFields = packagejson.ContentMapperFields
type DependencyFields = packagejson.DependencyFields
type Expected[T any] = packagejson.Expected[T]
type ExportsOrImports = packagejson.ExportsOrImports
type Fields = packagejson.Fields
type HeaderFields = packagejson.HeaderFields
type InfoCache = packagejson.InfoCache
type InfoCacheEntry = packagejson.InfoCacheEntry
type JSONValue = packagejson.JSONValue
type JSONValueType = packagejson.JSONValueType
const JSONValueTypeArray = packagejson.JSONValueTypeArray
const JSONValueTypeBoolean = packagejson.JSONValueTypeBoolean
const JSONValueTypeNotPresent = packagejson.JSONValueTypeNotPresent
const JSONValueTypeNull = packagejson.JSONValueTypeNull
const JSONValueTypeNumber = packagejson.JSONValueTypeNumber
const JSONValueTypeObject = packagejson.JSONValueTypeObject
const JSONValueTypeString = packagejson.JSONValueTypeString
//go:linkname NewInfoCache github.com/microsoft/TypeScript/tsc/internal/packagejson.NewInfoCache
func NewInfoCache(currentDirectory string, useCaseSensitiveFileNames bool) *packagejson.InfoCache
type PackageJson = packagejson.PackageJson
//go:linkname Parse github.com/microsoft/TypeScript/tsc/internal/packagejson.Parse
func Parse(data []byte) (packagejson.Fields, error)
type PathFields = packagejson.PathFields
type TypeValidatedField = packagejson.TypeValidatedField
type VersionPaths = packagejson.VersionPaths
