
// Code generated by _tools/gen_shims. DO NOT EDIT.

package repo

import _ "github.com/microsoft/TypeScript/tsc/internal/repo"
import _ "unsafe"

//go:linkname RootPath github.com/microsoft/TypeScript/tsc/internal/repo.RootPath
func RootPath() string
//go:linkname TestDataPath github.com/microsoft/TypeScript/tsc/internal/repo.TestDataPath
func TestDataPath() string
